# Sinh trên server rồi mang về repo (máy local không có Django).
# Generated by Django 4.2.30 on 2026-07-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # KHÔNG bám 0233: đó là migration rác mà makemigrations luôn tự sinh từ chỗ
        # lệch có sẵn của repo vnoj (choices của Profile.timezone lấy động từ pytz).
        # Nó không nằm trong repo nên bám vào là migration này chết ở máy khác.
        ('judge', '0232_hcmus_contest_hide_problem_statements'),
        ('hcmus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='hall_of_fame',
            field=models.PositiveIntegerField(default=0, help_text='Number of top teams highlighted in the table. The first three also get a gold, silver and bronze medal. Set to 0 to turn this off.', verbose_name='hall of fame size'),
        ),
        migrations.AddField(
            model_name='rankingcontest',
            name='setters',
            field=models.ManyToManyField(blank=True, help_text='Teams that set this contest. They receive the maximum score and zero penalty for it without competing.', related_name='+', to='judge.profile', verbose_name='problem setters'),
        ),
    ]
