# Generated by Django 4.2.30 on 2026-07-20 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # KHÔNG bám 0233: migration rác mà makemigrations luôn tự sinh từ chỗ lệch
        # có sẵn của vnoj (choices của Profile.timezone lấy động từ pytz). Nó không
        # nằm trong repo nên bám vào là migration này chết ở máy khác.
        ('judge', '0232_hcmus_contest_hide_problem_statements'),
        ('hcmus', '0002_ranking_hall_of_fame_rankingcontest_setters'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post', 'Blog post'), ('ranking', 'Team ranking'), ('contest', 'Contest'), ('custom', 'Custom content')], default='custom', max_length=16, verbose_name='kind')),
                ('title', models.CharField(blank=True, help_text='Leave empty to use the name of the linked object.', max_length=150, verbose_name='title')),
                ('content', models.TextField(blank=True, help_text='Markdown, for the "Custom content" kind.', verbose_name='content')),
                ('limit', models.PositiveIntegerField(default=10, help_text='For a ranking: how many teams to show. 0 shows every team.', verbose_name='rows shown')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judge.contest', verbose_name='contest')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judge.blogpost', verbose_name='blog post')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hcmus.ranking', verbose_name='team ranking')),
            ],
            options={
                'verbose_name': 'home page section',
                'verbose_name_plural': 'home page sections',
                'ordering': ['order'],
            },
        ),
    ]
