# Generated by Django 4.2.30 on 2026-07-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcmus', '0003_homesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='kind',
            field=models.CharField(choices=[('post', 'Blog post'), ('ranking', 'Team ranking'), ('contest', 'Contest'), ('custom', 'Custom content'), ('feed', 'Blog feed (the usual list of posts)')], default='custom', max_length=16, verbose_name='kind'),
        ),
    ]
