# Generated by Django 4.2.30 on 2026-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hcmus', '0004_alter_homesection_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Short name, e.g. ra-de', max_length=48, unique=True, verbose_name='identifier')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='display name')),
                ('note', models.TextField(blank=True, help_text='Why this set exists, what it is for.', verbose_name='note')),
                ('is_role', models.BooleanField(default=False, help_text='Roles become real groups you can assign to people. Leave off for building blocks that only exist to be combined into roles.', verbose_name='is a role')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('includes', models.ManyToManyField(blank=True, help_text='Everything in these sets is added to this one.', related_name='included_by', to='hcmus.permset', verbose_name='includes sets')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'permission set',
                'verbose_name_plural': 'permission sets',
                'ordering': ['order', 'name'],
            },
        ),
    ]
