# Generated by Django 4.2.30 on 2026-07-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcmus', '0005_permset'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must match the container name, e.g. judge3', max_length=50, unique=True, verbose_name='judge name')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last changed')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judge.profile', verbose_name='last changed by')),
            ],
            options={
                'verbose_name': 'judge switch',
                'verbose_name_plural': 'judge switches',
                'ordering': ['name'],
                'permissions': (('control_judges', 'Turn judges on and off'),),
            },
        ),
    ]
