# Generated by Django 4.2.30 on 2026-07-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_hcmus_contest_hide_problem_statements'),
        ('hcmus', '0006_judgeswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location', models.CharField(blank=True, help_text='Room, city, or a URL.', max_length=200, verbose_name='location')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='Leave empty for a point-in-time or all-day event.', null=True, verbose_name='end time')),
                ('all_day', models.BooleanField(default=False, verbose_name='all day')),
                ('visibility', models.CharField(choices=[('P', 'Public — anyone can see it, including in the subscribe feed'), ('O', 'Class — only members of the chosen classes'), ('I', 'Internal — only people with the "view internal calendar" permission')], default='P', max_length=1, verbose_name='visibility')),
                ('category', models.CharField(choices=[('icpc', 'ICPC / regional'), ('regional', 'Regional site'), ('training', 'Training session'), ('meeting', 'Meeting'), ('contest', 'Contest (non-system)'), ('other', 'Other')], default='other', max_length=16, verbose_name='category')),
                ('url', models.CharField(blank=True, help_text='Optional. Clicking the event opens this.', max_length=300, verbose_name='link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judge.profile', verbose_name='created by')),
                ('organizations', models.ManyToManyField(blank=True, help_text='Only used when visibility is "Class". Members of any of these classes see it.', related_name='calendar_events', to='judge.organization', verbose_name='classes')),
            ],
            options={
                'verbose_name': 'calendar event',
                'verbose_name_plural': 'calendar events',
                'ordering': ['start_time'],
                'permissions': (('view_internal_calendar', 'View internal calendar events'),),
                'indexes': [models.Index(fields=['visibility', 'start_time'], name='hcmus_calen_visibil_457cee_idx')],
            },
        ),
    ]
