# Generated by Django 4.2.30 on 2026-09-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_hcmus_contest_hide_problem_statements'),
        ('hcmus', '0017_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestprinter',
            name='allow_print',
            field=models.BooleanField(default=False, help_text='Bật để thí sinh được gửi yêu cầu in trong kỳ thi này. Yêu cầu vào hàng đợi, giám thị tải về và tự in.', verbose_name='allow printing'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='marked printed at'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judge.profile', verbose_name='marked printed by'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='pygments',
            field=models.CharField(blank=True, max_length=40, verbose_name='pygments lexer'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='source',
            field=models.TextField(blank=True, verbose_name='source code'),
        ),
        migrations.AlterField(
            model_name='contestprinter',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Chỉ dùng cho đường in thẳng qua CUPS. Cách in qua hàng đợi không cần máy in, để trống được.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hcmus.printer', verbose_name='printer'),
        ),
    ]
