# Generated by Django 4.2.30 on 2026-09-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_hcmus_contest_hide_problem_statements'),
        ('hcmus', '0018_contestprinter_allow_print_printrequest_printed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('C', 'Người'), ('B', 'Bot')], default='C', max_length=1, verbose_name='kind')),
                ('event', models.CharField(blank=True, help_text='Loại sự kiện nếu là tin của bot: print, ticket...', max_length=24, verbose_name='event')),
                ('body', models.TextField(verbose_name='content')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='link')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('retracted', models.BooleanField(default=False, verbose_name='retracted')),
                ('done', models.BooleanField(db_index=True, default=False, verbose_name='done')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='done at')),
                ('score', models.IntegerField(db_index=True, default=0, verbose_name='score')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='war_messages', to='judge.profile', verbose_name='author')),
                ('contest', models.ForeignKey(blank=True, help_text='Để trống là phòng chung, không gắn kỳ thi nào.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='war_messages', to='judge.contest', verbose_name='contest')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judge.profile', verbose_name='done by')),
                ('retracted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judge.profile', verbose_name='retracted by')),
            ],
            options={
                'verbose_name': 'war room message',
                'verbose_name_plural': 'war room messages',
                'ordering': ['-created'],
                'permissions': (('use_war_room', 'Use the war room (on-duty staff)'),),
            },
        ),
        migrations.CreateModel(
            name='WarVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, '+1'), (-1, '-1')])),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='hcmus.warmessage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judge.profile')),
            ],
            options={
                'verbose_name': 'war room vote',
                'verbose_name_plural': 'war room votes',
                'unique_together': {('message', 'profile')},
            },
        ),
    ]
