# Generated by Django 4.2.30 on 2026-10-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcmus', '0019_warmessage_warvote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warmessage',
            options={'ordering': ['-noi_bat', '-created'], 'permissions': (('use_war_room', 'Use the war room (on-duty staff)'),), 'verbose_name': 'war room message', 'verbose_name_plural': 'war room messages'},
        ),
        migrations.RemoveField(
            model_name='warmessage',
            name='score',
        ),
        migrations.AddField(
            model_name='warmessage',
            name='noi_bat',
            field=models.BooleanField(db_index=True, default=False, verbose_name='highlighted'),
        ),
        migrations.AddField(
            model_name='warmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hcmus.warmessage', verbose_name='reply to'),
        ),
        migrations.DeleteModel(
            name='WarVote',
        ),
    ]
