# Generated by Django 4.2.30 on 2026-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcmus', '0020_alter_warmessage_options_remove_warmessage_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestprinter',
            name='page_quota',
            field=models.PositiveIntegerField(default=20, help_text='Tổng số trang mỗi đội được in trong CẢ kỳ thi. Đặt 0 nếu không muốn giới hạn. Yêu cầu bị từ chối vì quá dài không tính vào đây.', verbose_name='page quota per team'),
        ),
    ]
