# Generated by Django 4.2.30 on 2026-10-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_hcmus_contest_hide_problem_statements'),
        ('hcmus', '0021_contestprinter_page_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarTim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tims', to='hcmus.warmessage', verbose_name='message')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_tims', to='judge.profile', verbose_name='who')),
            ],
            options={
                'verbose_name': 'war room heart',
                'verbose_name_plural': 'war room hearts',
                'ordering': ['created'],
                'unique_together': {('message', 'profile')},
            },
        ),
    ]
