# Generated by Django 4.2.30 on 2026-10-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_hcmus_contest_hide_problem_statements'),
        ('hcmus', '0022_wartim'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingcontest',
            name='diem_toi_da_ngoai',
            field=models.FloatField(blank=True, help_text='Highest score obtainable in that round, e.g. the number of problems. Used for the problem setters rule.', null=True, verbose_name='external maximum score'),
        ),
        migrations.AddField(
            model_name='rankingcontest',
            name='don_vi_penalty',
            field=models.CharField(choices=[('phut', 'minutes (ICPC format)'), ('giay', 'seconds (default format)')], default='phut', help_text='Unit of the penalty column in the imported file. ICPC counts minutes.', max_length=4, verbose_name='external penalty unit'),
        ),
        migrations.AddField(
            model_name='rankingcontest',
            name='ten_ngoai',
            field=models.CharField(blank=True, help_text='Fill this instead of picking a contest when the round was held on another server and the scoreboard was imported from a file.', max_length=150, verbose_name='external round name'),
        ),
        migrations.AlterField(
            model_name='rankingcontest',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judge.contest', verbose_name='contest'),
        ),
        migrations.CreateModel(
            name='RankingDongNgoai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_doi', models.CharField(max_length=150, verbose_name='team name in the file')),
                ('diem', models.FloatField(default=0, verbose_name='score')),
                ('penalty', models.IntegerField(default=0, verbose_name='penalty')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judge.profile', verbose_name='matched account')),
                ('rc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dong_ngoai', to='hcmus.rankingcontest', verbose_name='ranking column')),
            ],
            options={
                'verbose_name': 'imported scoreboard row',
                'verbose_name_plural': 'imported scoreboard rows',
                'ordering': ['-diem', 'penalty'],
                'unique_together': {('rc', 'profile')},
            },
        ),
    ]
